/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './favorite';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/components/list/list';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from 'ionic-angular/config/config';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from '../../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import23 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import24 from 'ionic-angular/util/keyboard';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from 'ionic-angular/components/tabs/tabs';
import * as import27 from 'ionic-angular/gestures/gesture-controller';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from 'ionic-angular/components/item/item-sliding';
import * as import31 from '@angular/core/src/linker/query_list';
import * as import32 from 'ionic-angular/components/item/item';
import * as import33 from '../../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
import * as import34 from '../../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from '@angular/core/src/security';
var renderType_FavoritePage_Host:import0.RenderComponentType = (null as any);
class _View_FavoritePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FavoritePage_0_4:import3.FavoritePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FavoritePage_Host0,renderType_FavoritePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FavoritePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FavoritePage_0_4 = new import3.FavoritePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._FavoritePage_0_4,([] as any[]),compView_0);
    compView_0.create(this._FavoritePage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FavoritePage) && (0 === requestNodeIndex))) { return this._FavoritePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FavoritePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FavoritePage_Host === (null as any))) { (renderType_FavoritePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_FavoritePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const FavoritePageNgFactory:import10.ComponentFactory<import3.FavoritePage> = new import10.ComponentFactory<import3.FavoritePage>('ng-component',viewFactory_FavoritePage_Host0,import3.FavoritePage);
const styles_FavoritePage:any[] = ([] as any[]);
var renderType_FavoritePage:import0.RenderComponentType = (null as any);
class _View_FavoritePage0 extends import1.AppView<import3.FavoritePage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import13.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import14.Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import15.List;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgFor_13_6:import16.NgFor;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FavoritePage0,renderType_FavoritePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import19.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import20.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import21.App),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import22.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.ToolbarTitle(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Favorites',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import23.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Content(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import26.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_11_3 = new import15.List(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import27.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_13 = new import2.AppElement(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import28.TemplateRef_(this._appEl_13,viewFactory_FavoritePage1);
    this._NgFor_13_6 = new import16.NgFor(this._appEl_13.vcRef,this._TemplateRef_13_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_14 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_15
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import28.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import16.NgFor) && (13 === requestNodeIndex))) { return this._NgFor_13_6; }
    if (((token === import15.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._List_11_3; }
    if (((token === import14.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changes = (null as any);
    const currVal_4:any = this.context.favoriteList;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_13_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_13_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_13_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_FavoritePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FavoritePage> {
  if ((renderType_FavoritePage === (null as any))) { (renderType_FavoritePage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_FavoritePage,{})); }
  return new _View_FavoritePage0(viewUtils,parentInjector,declarationEl);
}
class _View_FavoritePage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import30.ItemSliding;
  _query_Item_0_0:import31.QueryList<any>;
  _query_ItemOptions_0_1:import31.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import32.Item;
  _ItemContent_2_5:import32.ItemContent;
  _query_Label_2_0:import31.QueryList<any>;
  _query_Button_2_1:import31.QueryList<any>;
  _query_Icon_2_2:import31.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _ItemOptions_10_3:import30.ItemOptions;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FavoritePage1,renderType_FavoritePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import33.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import30.ItemSliding((<_View_FavoritePage0>this.parent)._List_11_3,this.renderer,new import18.ElementRef(this._el_0),this.parent.parentInjector.get(import25.NgZone));
    this._query_Item_0_0 = new import31.QueryList<any>();
    this._query_ItemOptions_0_1 = new import31.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import34.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import32.Item(this.parent.parentInjector.get(import35.Form),this.parent.parentInjector.get(import17.Config),new import18.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import32.ItemContent();
    this._query_Label_2_0 = new import31.QueryList<any>();
    this._query_Button_2_1 = new import31.QueryList<any>();
    this._query_Icon_2_2 = new import31.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'item-right','');
    this.renderer.setElementAttribute(this._el_6,'outline','');
    this._text_7 = this.renderer.createText(this._el_6,'Read',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_5,
        this._text_8
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_6])
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this._ItemOptions_10_3 = new import30.ItemOptions(new import18.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'color','primary');
    this._text_13 = this.renderer.createText(this._el_12,'Delete',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([this._el_10])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_2_4; }
    if (((token === import32.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ItemContent_2_5; }
    if (((token === import30.ItemOptions) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemOptions_10_3; }
    if (((token === import30.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_10_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.post.title.rendered;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_4,'innerHTML',this.viewUtils.sanitizer.sanitize(import36.SecurityContext.HTML,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.read(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.removeFavorite(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_FavoritePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FavoritePage1(viewUtils,parentInjector,declarationEl);
}