/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './post';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from 'ionic-angular/components/list/list';
import * as import17 from 'ionic-angular/components/card/card';
import * as import18 from 'ionic-angular/components/item/item';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from 'angular2-moment/time-ago.pipe';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from '../../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import28 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/gestures/gesture-controller';
import * as import33 from '../../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import34 from 'ionic-angular/util/form';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '@angular/core/src/security';
var renderType_PostPage_Host:import0.RenderComponentType = (null as any);
class _View_PostPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PostPage_0_4:import3.PostPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PostPage_Host0,renderType_PostPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PostPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PostPage_0_4 = new import3.PostPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._PostPage_0_4,([] as any[]),compView_0);
    compView_0.create(this._PostPage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PostPage) && (0 === requestNodeIndex))) { return this._PostPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PostPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PostPage_Host === (null as any))) { (renderType_PostPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PostPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PostPageNgFactory:import11.ComponentFactory<import3.PostPage> = new import11.ComponentFactory<import3.PostPage>('ng-component',viewFactory_PostPage_Host0,import3.PostPage);
const styles_PostPage:any[] = ([] as any[]);
var renderType_PostPage:import0.RenderComponentType = (null as any);
class _View_PostPage0 extends import1.AppView<import3.PostPage> {
  _el_0:any;
  _Header_0_3:import12.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import13.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import14.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import15.Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import16.List;
  _text_12:any;
  _el_13:any;
  _Card_13_3:import17.Card;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Item_15_4:import18.Item;
  _ItemContent_15_5:import18.ItemContent;
  _query_Label_15_0:import19.QueryList<any>;
  _query_Button_15_1:import19.QueryList<any>;
  _query_Icon_15_2:import19.QueryList<any>;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _Card_24_3:import17.Card;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import20.NgIf;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _pipe_amTimeAgo_0:import21.TimeAgoPipe;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PostPage0,renderType_PostPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import25.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import27.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.ToolbarTitle(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Caption View',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','post');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import28.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_11_3 = new import16.List(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import32.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-card',(null as any));
    this._Card_13_3 = new import17.Card(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'\n\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','post-title item item-block');
    this.renderer.setElementAttribute(this._el_15,'text-wrap','');
    this._appEl_15 = new import2.AppElement(15,13,this,this._el_15);
    var compView_15:any = import33.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import18.Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import18.ItemContent();
    this._query_Label_15_0 = new import19.QueryList<any>();
    this._query_Button_15_1 = new import19.QueryList<any>();
    this._query_Icon_15_2 = new import19.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','date');
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_15_0.reset(([] as any[]));
    this._Item_15_4.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_18,
        this._el_19,
        this._text_21
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n        \n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_11,'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_24,'text-wrap','');
    this._Card_24_3 = new import17.Card(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_24),this.renderer);
    this._text_25 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_26 = new import2.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import35.TemplateRef_(this._appEl_26,viewFactory_PostPage1);
    this._NgIf_26_6 = new import20.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_24,'\n         ',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_30
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._pipe_amTimeAgo_0 = new import21.TimeAgoPipe(this.ref,this.parentInjector.get(import30.NgZone));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import13.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import12.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import18.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_15_4; }
    if (((token === import18.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_15_5; }
    if (((token === import17.Card) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Card_13_3; }
    if (((token === import35.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import20.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    if (((token === import17.Card) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Card_24_3; }
    if (((token === import16.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._List_11_3; }
    if (((token === import15.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_6:any = this.context.postData.images;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_26_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset(([] as any[]));
        this._Item_15_4._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset(([] as any[]));
        this._Item_15_4._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_15_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.postData.post.title.rendered;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_17,'innerHTML',this.viewUtils.sanitizer.sanitize(import36.SecurityContext.HTML,currVal_4));
      this._expr_4 = currVal_4;
    }
    valUnwrapper.reset();
    const currVal_5:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_amTimeAgo_0.transform(this.context.postData.post.date)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_5,currVal_5))) {
      this.renderer.setText(this._text_20,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
    this._pipe_amTimeAgo_0.ngOnDestroy();
  }
}
export function viewFactory_PostPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PostPage> {
  if ((renderType_PostPage === (null as any))) { (renderType_PostPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_PostPage,{})); }
  return new _View_PostPage0(viewUtils,parentInjector,declarationEl);
}
class _View_PostPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PostPage1,renderType_PostPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.postData.images.source_url;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import36.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PostPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PostPage1(viewUtils,parentInjector,declarationEl);
}