/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '../providers/util-provider/util-provider';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from 'ionic-angular/components/nav/nav';
import * as import14 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import15 from 'ionic-angular/navigation/view-controller';
import * as import16 from 'ionic-angular/navigation/nav-controller-base';
import * as import17 from 'ionic-angular/components/app/app';
import * as import18 from 'ionic-angular/config/config';
import * as import19 from 'ionic-angular/util/keyboard';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from 'ionic-angular/gestures/gesture-controller';
import * as import24 from 'ionic-angular/transitions/transition-controller';
import * as import25 from 'ionic-angular/navigation/deep-linker';
var renderType_CaptionApp_Host:import0.RenderComponentType = (null as any);
class _View_CaptionApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CaptionApp_0_4:import3.CaptionApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CaptionApp_Host0,renderType_CaptionApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CaptionApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CaptionApp_0_4 = new import3.CaptionApp(this.parentInjector.get(import8.Platform),this.parentInjector.get(import9.UtilProvider));
    this._appEl_0.initComponent(this._CaptionApp_0_4,([] as any[]),compView_0);
    compView_0.create(this._CaptionApp_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CaptionApp) && (0 === requestNodeIndex))) { return this._CaptionApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CaptionApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CaptionApp_Host === (null as any))) { (renderType_CaptionApp_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_CaptionApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const CaptionAppNgFactory:import11.ComponentFactory<import3.CaptionApp> = new import11.ComponentFactory<import3.CaptionApp>('ng-component',viewFactory_CaptionApp_Host0,import3.CaptionApp);
const styles_CaptionApp:any[] = ([] as any[]);
var renderType_CaptionApp:import0.RenderComponentType = (null as any);
class _View_CaptionApp0 extends import1.AppView<import3.CaptionApp> {
  _viewQuery_Nav_0:import12.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Nav_0_4:import13.Nav;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CaptionApp0,renderType_CaptionApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import12.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','nav');
    this.renderer.setElementAttribute(this._el_0,'swipeBackEnabled','false');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import14.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import13.Nav(this.parentInjector.get(import15.ViewController,(null as any)),this.parentInjector.get(import16.NavControllerBase,(null as any)),this.parentInjector.get(import17.App),this.parentInjector.get(import18.Config),this.parentInjector.get(import19.Keyboard),new import20.ElementRef(this._el_0),this.parentInjector.get(import21.NgZone),this.renderer,this.parentInjector.get(import22.ComponentFactoryResolver),this.parentInjector.get(import23.GestureController),this.parentInjector.get(import24.TransitionController),this.parentInjector.get(import25.DeepLinker,(null as any)));
    this._appEl_0.initComponent(this._Nav_0_4,([] as any[]),compView_0);
    compView_0.create(this._Nav_0_4,([] as any[]),(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_0_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'false';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Nav_0_4.swipeBackEnabled = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_CaptionApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CaptionApp> {
  if ((renderType_CaptionApp === (null as any))) { (renderType_CaptionApp = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_CaptionApp,{})); }
  return new _View_CaptionApp0(viewUtils,parentInjector,declarationEl);
}