/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './post';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../providers/wp-provider/wp-provider';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/item/item-sliding';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from 'ionic-angular/components/item/item';
import * as import14 from 'ionic-angular/components/avatar/avatar';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from 'ionic-angular/components/grid/grid';
import * as import17 from 'ionic-angular/components/icon/icon';
import * as import18 from 'angular2-moment/time-ago.pipe';
import * as import19 from '../../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/core/src/zone/ng_zone';
import * as import23 from '../../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import24 from 'ionic-angular/util/form';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '@angular/core/src/security';
var renderType_PostCmp_Host:import0.RenderComponentType = (null as any);
class _View_PostCmp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PostCmp_0_4:import3.PostCmp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PostCmp_Host0,renderType_PostCmp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('post',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PostCmp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PostCmp_0_4 = new import3.PostCmp(this.parentInjector.get(import8.WpProvider));
    this._appEl_0.initComponent(this._PostCmp_0_4,([] as any[]),compView_0);
    compView_0.create(this._PostCmp_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PostCmp) && (0 === requestNodeIndex))) { return this._PostCmp_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._PostCmp_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PostCmp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PostCmp_Host === (null as any))) { (renderType_PostCmp_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PostCmp_Host0(viewUtils,parentInjector,declarationEl);
}
export const PostCmpNgFactory:import10.ComponentFactory<import3.PostCmp> = new import10.ComponentFactory<import3.PostCmp>('post',viewFactory_PostCmp_Host0,import3.PostCmp);
const styles_PostCmp:any[] = ([] as any[]);
var renderType_PostCmp:import0.RenderComponentType = (null as any);
class _View_PostCmp0 extends import1.AppView<import3.PostCmp> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import11.ItemSliding;
  _query_Item_0_0:import12.QueryList<any>;
  _query_ItemOptions_0_1:import12.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import13.Item;
  _ItemContent_2_5:import13.ItemContent;
  _query_Label_2_0:import12.QueryList<any>;
  _query_Button_2_1:import12.QueryList<any>;
  _query_Icon_2_2:import12.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Avatar_4_3:import14.Avatar;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import15.NgIf;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _Row_14_3:import16.Row;
  _text_15:any;
  _el_16:any;
  _Col_16_3:import16.Col;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _Icon_20_3:import17.Icon;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import16.Col;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _Icon_28_3:import17.Icon;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _Col_32_3:import16.Col;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _Icon_36_3:import17.Icon;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _ItemOptions_42_3:import11.ItemOptions;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _Icon_46_3:import17.Icon;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _Icon_51_3:import17.Icon;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _ItemOptions_55_3:import11.ItemOptions;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _Icon_59_3:import17.Icon;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _Icon_64_3:import17.Icon;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  _pipe_amTimeAgo_0:import18.TimeAgoPipe;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PostCmp0,renderType_PostCmp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-item-sliding',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','post-cmp');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import19.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import11.ItemSliding(this.parentInjector.get(import20.List,(null as any)),this.renderer,new import21.ElementRef(this._el_0),this.parentInjector.get(import22.NgZone));
    this._query_Item_0_0 = new import12.QueryList<any>();
    this._query_ItemOptions_0_1 = new import12.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'no-padding','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import23.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import13.Item(this.parentInjector.get(import24.Form),this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import13.ItemContent();
    this._query_Label_2_0 = new import12.QueryList<any>();
    this._query_Button_2_1 = new import12.QueryList<any>();
    this._query_Icon_2_2 = new import12.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Avatar_4_3 = new import14.Avatar();
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import26.TemplateRef_(this._appEl_6,viewFactory_PostCmp1);
    this._NgIf_6_6 = new import15.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_4,'\n\n    ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','post-title');
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_14,'no-padding','');
    this._Row_14_3 = new import16.Row();
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_16,'no-padding','');
    this._Col_16_3 = new import16.Col();
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'clear','');
    this.renderer.setElementAttribute(this._el_18,'color','danger');
    this.renderer.setElementAttribute(this._el_18,'small','');
    this._text_19 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_20,'name','book');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText(this._el_18,'\n          Read\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_14,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'no-padding','');
    this.renderer.setElementAttribute(this._el_24,'text-center','');
    this._Col_24_3 = new import16.Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'clear','');
    this.renderer.setElementAttribute(this._el_26,'color','danger');
    this.renderer.setElementAttribute(this._el_26,'small','');
    this._text_27 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','bookmark');
    this.renderer.setElementAttribute(this._el_28,'role','img');
    this._Icon_28_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_26,'\n          Star\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_31 = this.renderer.createText(this._el_14,'\n\n      ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_14,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_32,'no-padding','');
    this.renderer.setElementAttribute(this._el_32,'text-right','');
    this._Col_32_3 = new import16.Col();
    this._text_33 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'button',(null as any));
    this.renderer.setElementAttribute(this._el_34,'clear','');
    this.renderer.setElementAttribute(this._el_34,'color','danger');
    this.renderer.setElementAttribute(this._el_34,'small','');
    this._text_35 = this.renderer.createText(this._el_34,'\n          ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_36,'name','share-alt');
    this.renderer.setElementAttribute(this._el_36,'role','img');
    this._Icon_36_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText(this._el_34,'\n          Share\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_32,'\n      ',(null as any));
    this._text_39 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_40
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this.renderer.setElementAttribute(this._el_42,'side','left');
    this._ItemOptions_42_3 = new import11.ItemOptions(new import21.ElementRef(this._el_42),this.renderer);
    this._text_43 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'color','danger');
    this._text_45 = this.renderer.createText(this._el_44,' \n        ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_46,'name','bookmark');
    this.renderer.setElementAttribute(this._el_46,'role','img');
    this._Icon_46_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_46),this.renderer);
    this._text_47 = this.renderer.createText(this._el_44,'\n        Star\n      ',(null as any));
    this._text_48 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_42,'button',(null as any));
    this.renderer.setElementAttribute(this._el_49,'color','secondary');
    this._text_50 = this.renderer.createText(this._el_49,' \n        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_51,'name','share-alt');
    this.renderer.setElementAttribute(this._el_51,'role','img');
    this._Icon_51_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_51),this.renderer);
    this._text_52 = this.renderer.createText(this._el_49,'\n        Share\n      ',(null as any));
    this._text_53 = this.renderer.createText(this._el_42,'\n  ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this.renderer.setElementAttribute(this._el_55,'side','right');
    this._ItemOptions_55_3 = new import11.ItemOptions(new import21.ElementRef(this._el_55),this.renderer);
    this._text_56 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'button',(null as any));
    this.renderer.setElementAttribute(this._el_57,'color','danger');
    this._text_58 = this.renderer.createText(this._el_57,' \n        ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_59,'name','bookmark');
    this.renderer.setElementAttribute(this._el_59,'role','img');
    this._Icon_59_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_59),this.renderer);
    this._text_60 = this.renderer.createText(this._el_57,'\n        Star\n      ',(null as any));
    this._text_61 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_55,'button',(null as any));
    this.renderer.setElementAttribute(this._el_62,'color','secondary');
    this._text_63 = this.renderer.createText(this._el_62,' \n        ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_62,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_64,'name','share-alt');
    this.renderer.setElementAttribute(this._el_64,'role','img');
    this._Icon_64_3 = new import17.Icon(this.parentInjector.get(import25.Config),new import21.ElementRef(this._el_64),this.renderer);
    this._text_65 = this.renderer.createText(this._el_62,'\n        Share\n      ',(null as any));
    this._text_66 = this.renderer.createText(this._el_55,'\n  ',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._el_42,
        this._el_55
      ]
      )
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._pipe_amTimeAgo_0 = new import18.TimeAgoPipe(this.ref,this.parentInjector.get(import22.NgZone));
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_49,'click',this.eventHandler(this._handle_click_49_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_57,'click',this.eventHandler(this._handle_click_57_0.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_62,'click',this.eventHandler(this._handle_click_62_0.bind(this)));
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import15.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import14.Avatar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Avatar_4_3; }
    if (((token === import17.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3; }
    if (((token === import16.Col) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Col_16_3; }
    if (((token === import17.Icon) && (28 === requestNodeIndex))) { return this._Icon_28_3; }
    if (((token === import16.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Col_24_3; }
    if (((token === import17.Icon) && (36 === requestNodeIndex))) { return this._Icon_36_3; }
    if (((token === import16.Col) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Col_32_3; }
    if (((token === import16.Row) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Row_14_3; }
    if (((token === import13.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_2_4; }
    if (((token === import13.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_2_5; }
    if (((token === import17.Icon) && (46 === requestNodeIndex))) { return this._Icon_46_3; }
    if (((token === import17.Icon) && (51 === requestNodeIndex))) { return this._Icon_51_3; }
    if (((token === import11.ItemOptions) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ItemOptions_42_3; }
    if (((token === import17.Icon) && (59 === requestNodeIndex))) { return this._Icon_59_3; }
    if (((token === import17.Icon) && (64 === requestNodeIndex))) { return this._Icon_64_3; }
    if (((token === import11.ItemOptions) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._ItemOptions_55_3; }
    if (((token === import11.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = this.context.postData.better_featured_image.media_details.sizes.thumbnail;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_6_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = 'book';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_20_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = 'bookmark';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_28_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = 'share-alt';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_36_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = 'left';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._ItemOptions_42_3.side = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = 'bookmark';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Icon_46_3.name = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = 'share-alt';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._Icon_51_3.name = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = 'right';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._ItemOptions_55_3.side = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_21:any = 'bookmark';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._Icon_59_3.name = currVal_21;
      this._expr_21 = currVal_21;
    }
    const currVal_24:any = 'share-alt';
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._Icon_64_3.name = currVal_24;
      this._expr_24 = currVal_24;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([
          this._ItemOptions_42_3,
          this._ItemOptions_55_3
        ]
        );
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this.context.postData.title.rendered;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_9,'innerHTML',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
    valUnwrapper.reset();
    const currVal_2:any = import4.interpolate(1,'Posted ',valUnwrapper.unwrap(this._pipe_amTimeAgo_0.transform(this.context.postData.date)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this.renderer.setText(this._text_12,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Icon_20_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_20,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_28_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_28,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._Icon_36_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_36,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_15:any = this._Icon_46_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_46,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_18:any = this._Icon_51_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_51,'hide',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._Icon_59_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_59,'hide',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_25:any = this._Icon_64_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_64,'hide',currVal_25);
      this._expr_25 = currVal_25;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_20_3.ngOnDestroy();
    this._Icon_28_3.ngOnDestroy();
    this._Icon_36_3.ngOnDestroy();
    this._Icon_46_3.ngOnDestroy();
    this._Icon_51_3.ngOnDestroy();
    this._Icon_59_3.ngOnDestroy();
    this._Icon_64_3.ngOnDestroy();
    this._pipe_amTimeAgo_0.ngOnDestroy();
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.readBtn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.favoriteBtn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.shareBtn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.favoriteBtn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_49_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.shareBtn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_57_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.favoriteBtn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_62_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.shareBtn()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PostCmp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PostCmp> {
  if ((renderType_PostCmp === (null as any))) { (renderType_PostCmp = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_PostCmp,{})); }
  return new _View_PostCmp0(viewUtils,parentInjector,declarationEl);
}
class _View_PostCmp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PostCmp1,renderType_PostCmp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.postData.better_featured_image.media_details.sizes.thumbnail.source_url;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PostCmp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PostCmp1(viewUtils,parentInjector,declarationEl);
}